# Generated by Django 5.1.4 on 2025-12-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnualReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="files/annual_reports/"
                    ),
                ),
                ("file_size", models.CharField(blank=True, max_length=50, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("issuer", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField()),
                (
                    "icon_svg",
                    models.ImageField(blank=True, null=True, upload_to="images/icons/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-year"],
            },
        ),
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("qualifications", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="images/board/"),
                ),
                ("social_links", models.JSONField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vice_president", "Vice President"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                            ("board_member", "Board Member"),
                            ("other", "Other"),
                        ],
                        default="board_member",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CallToAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage"),
                            ("about", "About"),
                            ("knowledge_center", "Knowledge Center"),
                            ("member_directory", "Member Directory"),
                            ("news_and_updates", "News and Updates"),
                            ("research_and_publications", "Research and Publications"),
                            ("webinars", "Webinars"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "primary_button_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "secondary_button_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("primary_button_url", models.URLField(blank=True, null=True)),
                ("secondary_button_url", models.URLField(blank=True, null=True)),
                (
                    "background_svg",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/backgrounds/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("link_to_members", models.URLField(blank=True, null=True)),
                (
                    "icon_svg",
                    models.ImageField(blank=True, null=True, upload_to="images/icons/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                            ("webinar", "Webinar"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("registration_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "date"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage"),
                            ("about", "About"),
                            ("knowledge_center", "Knowledge Center"),
                            ("member_directory", "Member Directory"),
                            ("news_and_updates", "News and Updates"),
                            ("research_and_publications", "Research and Publications"),
                            ("webinars", "Webinars"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True, null=True)),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="images/hero/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/members/"
                    ),
                ),
                ("profile_url", models.URLField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("url_name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NewsTickerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationalValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("mission", "Mission"),
                            ("vision", "Vision"),
                            ("value", "Value"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "icon_svg",
                    models.ImageField(blank=True, null=True, upload_to="images/icons/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Organizational Values",
                "ordering": ["value_type", "order"],
            },
        ),
        migrations.CreateModel(
            name="Panelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/panelists/"
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/partnership/"
                    ),
                ),
                ("link_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuickAccessCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage"),
                            ("about", "About"),
                            ("knowledge_center", "Knowledge Center"),
                            ("member_directory", "Member Directory"),
                            ("news_and_updates", "News and Updates"),
                            ("research_and_publications", "Research and Publications"),
                            ("webinars", "Webinars"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon_svg",
                    models.ImageField(blank=True, null=True, upload_to="images/icons/"),
                ),
                ("link_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResearchHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                (
                    "lead_researcher_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lead_researcher_image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/researchers/"
                    ),
                ),
                (
                    "journal_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("journal_link", models.URLField(blank=True, null=True)),
                ("highlight", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResearchInterestArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="BSBCS", max_length=255)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tag_line", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site_settings/"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="site_settings/"
                    ),
                ),
                ("footer_content", models.TextField(blank=True, null=True)),
                (
                    "contact_mail",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "footer_copyright",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StatisticCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage"),
                            ("about", "About"),
                            ("knowledge_center", "Knowledge Center"),
                            ("member_directory", "Member Directory"),
                            ("news_and_updates", "News and Updates"),
                            ("research_and_publications", "Research and Publications"),
                            ("webinars", "Webinars"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("count_text", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon_svg",
                    models.ImageField(blank=True, null=True, upload_to="images/icons/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimelineSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("intro", models.TextField(blank=True, null=True)),
                (
                    "icon_svg",
                    models.ImageField(blank=True, null=True, upload_to="images/icons/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CarouselItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/carousel/"
                    ),
                ),
                ("badge_text", models.CharField(blank=True, max_length=50, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "hero_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_items",
                        to="website.herosection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ResourceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("guideline", "Guideline"),
                            ("research_publication", "Research Publication"),
                            ("educational_material", "Educational Material"),
                            ("tool", "Tool"),
                            ("webinar", "Webinar"),
                        ],
                        max_length=50,
                    ),
                ),
                ("updated_date", models.DateField(blank=True, null=True)),
                (
                    "file_upload",
                    models.FileField(
                        blank=True, null=True, upload_to="files/resources/"
                    ),
                ),
                ("external_link", models.URLField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="website.resourcecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("profile_description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/members/"
                    ),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "research_interest_areas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="members",
                        to="website.researchinterestarea",
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="members_specialties",
                        to="website.speciality",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TimelineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon_svg",
                    models.ImageField(blank=True, null=True, upload_to="images/icons/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="website.timelinesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Webinar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("perceptorship", "Percepetoship"),
                            ("webinar", "Webinar"),
                            ("gci", "GCI"),
                            ("other", "Other"),
                        ],
                        default="webinar",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "presenter_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "presenter_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/presenters/"
                    ),
                ),
                ("recorded_date", models.DateField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("slides_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "international_panel",
                    models.ManyToManyField(
                        blank=True,
                        related_name="international_panel_webinars",
                        to="website.panelist",
                    ),
                ),
                (
                    "moderators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="moderated_webinars",
                        to="website.panelist",
                    ),
                ),
                (
                    "national_panel",
                    models.ManyToManyField(
                        blank=True,
                        related_name="national_panel_webinars",
                        to="website.panelist",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
