# Generated by Django 5.1.4 on 2025-12-08 07:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0063_alter_abouttheconference_image_and_more"),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="location",
        ),
        migrations.RemoveField(
            model_name="member",
            name="name",
        ),
        migrations.RemoveField(
            model_name="member",
            name="years_of_experience",
        ),
        migrations.AddField(
            model_name="member",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="member",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="member",
            name="user_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member",
                to="registration.userprofile",
            ),
        ),
    ]
