# Generated by Django 5.1.4 on 2026-03-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_alter_abouttheconference_image_and_more'),
        ('website', '0002_remove_member_location_remove_member_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('date_text', models.CharField(help_text='e.g. 11 November 2022', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(blank=True, help_text='e.g. Pan Pacific Sonargaon, Dhaka', max_length=255, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='past_events/logos/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='past_events/hero/')),
                ('about_image', models.ImageField(blank=True, help_text="Image for the 'About' section", null=True, upload_to='past_events/about/')),
                ('organizer', models.CharField(default='Bangladesh Society for Breast Cancer Study (BSBCS)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.navigationlink'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', max_length=10)),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True)),
                ('custom_event_name', models.CharField(blank=True, help_text="Enter event name if it's not in the registration app", max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_event', models.ForeignKey(blank=True, limit_choices_to={'event_status': 'closed'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_media', to='registration.event')),
            ],
            options={
                'verbose_name_plural': 'Media Gallery',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PastEventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(help_text='e.g. Day 1 or Nov 10', max_length=100)),
                ('session_name', models.CharField(help_text='e.g. Radiation Oncology', max_length=255)),
                ('time_range', models.CharField(help_text='e.g. 09:00 AM – 09:40 AM', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='website.pastevent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PastEventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('speaker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chairmen', models.TextField(blank=True, help_text='Comma separated names', null=True)),
                ('moderators', models.TextField(blank=True, help_text='Comma separated names', null=True)),
                ('panelists', models.TextField(blank=True, help_text='Comma separated names', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_activities', to='website.pastevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='website.pasteventsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PastEventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='past_events/speakers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='website.pastevent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PastEventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, help_text='e.g. Platinum, Golden', max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='past_events/sponsors/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='website.pastevent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
