# Generated by Django 5.1.4 on 2026-03-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_pastevent_navigationlink_is_dropdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteventsession',
            name='chairmen',
            field=models.TextField(blank=True, help_text='Comma separated names', null=True),
        ),
        migrations.AddField(
            model_name='pasteventsession',
            name='moderators',
            field=models.TextField(blank=True, help_text='Comma separated names', null=True),
        ),
        migrations.AddField(
            model_name='pasteventsession',
            name='panelists',
            field=models.TextField(blank=True, help_text='Comma separated names', null=True),
        ),
    ]
