# Generated by Django 5.1.4 on 2026-03-28 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_alter_abouttheconference_image_and_more'),
        ('website', '0004_pasteventsession_chairmen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_years', models.PositiveIntegerField(default=1, help_text='Default duration in years. For lifetime, this can be 100.')),
                ('is_lifetime', models.BooleanField(default=False, help_text='Mark this as a lifetime membership to disable duration selection in UI')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.AddField(
            model_name='member',
            name='is_active_member',
            field=models.BooleanField(default=False, help_text='Designates whether this member has an active subscription'),
        ),
        migrations.AddField(
            model_name='member',
            name='subscription_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_facilities',
            field=models.TextField(blank=True, help_text='List of facilities/benefits for members', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_invoice_logo',
            field=models.ImageField(blank=True, help_text='Logo specifically for membership invoices', null=True, upload_to='site_settings/invoices/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_subscription_enabled',
            field=models.BooleanField(default=False, help_text='Enable/Disable membership subscription system'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_yearly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default yearly membership fee (deprecated if types are used)', max_digits=10),
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_years', models.PositiveIntegerField(default=1)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_invoice_number', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('trxID', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='membership_invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to='registration.userprofile')),
                ('membership_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.membershiptype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.membershiptype'),
        ),
    ]
