# Generated by Django 5.1.4 on 2026-05-16

import django.db.models.deletion
from django.db import migrations, models


def create_default_membership_benefits(apps, schema_editor):
    MembershipBenefitModal = apps.get_model('website', 'MembershipBenefitModal')
    MembershipBenefitItem = apps.get_model('website', 'MembershipBenefitItem')

    modal = MembershipBenefitModal.objects.create(
        title='Become a BSBCS Member',
        subtitle='Membership Benefits',
        description=(
            'Join a professional society dedicated to breast cancer study, education, '
            'collaboration, and patient-centered care.'
        ),
        primary_button_text='Apply for Membership',
        secondary_button_text='Maybe Later',
        is_active=True,
    )

    benefits = [
        (
            'Selected event benefits',
            'Eligible members may receive discounted or complimentary access to selected BSBCS events.',
        ),
        (
            'Professional network',
            'Connect with clinicians, researchers, educators, and society programs.',
        ),
        (
            'Member directory visibility',
            'Approved active members can be listed in the public member directory.',
        ),
        (
            'Academic updates',
            'Stay connected with webinars, research updates, conferences, and society activities.',
        ),
    ]

    for index, (title, description) in enumerate(benefits, start=1):
        MembershipBenefitItem.objects.create(
            modal=modal,
            title=title,
            description=description,
            order=index,
            is_active=True,
        )


def remove_default_membership_benefits(apps, schema_editor):
    MembershipBenefitModal = apps.get_model('website', 'MembershipBenefitModal')
    MembershipBenefitModal.objects.filter(title='Become a BSBCS Member').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_membershiptype_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipBenefitModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Become a BSBCS Member', max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='membership/benefits/')),
                ('primary_button_text', models.CharField(default='Apply for Membership', max_length=80)),
                ('secondary_button_text', models.CharField(default='Maybe Later', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Benefit Modal',
                'verbose_name_plural': 'Membership Benefit Modal',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipBenefitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='membership/benefit_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('modal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_items', to='website.membershipbenefitmodal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(create_default_membership_benefits, remove_default_membership_benefits),
    ]
