# Generated by Django 5.1.4 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_membershipbenefitmodal_membershipbenefititem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipbenefitmodal',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Optional image-only modal. Recommended size: 1200x800 px, 3:2 ratio. If uploaded, this image is shown instead of text benefits.',
                null=True,
                upload_to='membership/benefits/',
            ),
        ),
    ]
