# Generated by Django 5.1.4 on 2026-05-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0065_event_registration_audience'),
        ('website', '0007_alter_membershipbenefitmodal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEventIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_type', models.CharField(choices=[('member_registration', 'Member event registration')], default='member_registration', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_intents', to='registration.event')),
                ('participant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_intent', to='registration.participant')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_event_intents', to='registration.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user_profile', 'event', 'intent_type')},
            },
        ),
    ]
