# Generated by Django 5.1.4 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_pendingeventintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipbenefitmodal',
            name='show_on_homepage',
            field=models.BooleanField(
                default=False,
                help_text='Automatically open this modal on the website homepage.',
            ),
        ),
    ]
