# Generated by Django 5.1.4 on 2024-12-06 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=500)),
                ('institution', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
                ('methods', models.TextField()),
                ('results', models.TextField()),
                ('conclusion', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/abstract_images/')),
                ('approved_for_presentation', models.BooleanField(default=False)),
                ('approved_for_poster', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
            options={
                'verbose_name_plural': 'Abstract Submission',
            },
        ),
        migrations.CreateModel(
            name='AboutTheConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/about_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
            options={
                'verbose_name_plural': 'About the Conference',
            },
        ),
        migrations.CreateModel(
            name='FeatureSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('biography', models.TextField(default='No biography available')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
            options={
                'verbose_name_plural': 'Feature Speakers',
            },
        ),
        migrations.CreateModel(
            name='HallRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
            options={
                'verbose_name_plural': 'Hall Room',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/invitation_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('year_of_graduation', models.IntegerField()),
                ('organization', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('BMDC_registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('denied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.department')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Day 1', max_length=50)),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
            options={
                'verbose_name_plural': 'Program Day',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/sponsor_images/')),
                ('category', models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Golden', 'Golden'), ('Silver', 'Silver'), ('Logistics', 'Logistics'), ('Media', 'Media'), ('IT', 'IT'), ('Event', 'Event')], max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
                ('hall_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='registration.hallroom')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProgramDay', to='registration.programday')),
            ],
            options={
                'verbose_name_plural': 'Time Slot',
            },
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenter', models.TextField(blank=True, null=True)),
                ('abstract_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.abstractsubmission')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
                ('time_slots', models.ManyToManyField(related_name='schedules', to='registration.timeslot')),
            ],
            options={
                'verbose_name_plural': 'Program Schedule',
            },
        ),
    ]
