# Generated by Django 5.1.4 on 2024-12-08 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_chairperson_moderator_panelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschedule',
            name='chairperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.chairperson'),
        ),
        migrations.AddField(
            model_name='programschedule',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.moderator'),
        ),
        migrations.AddField(
            model_name='programschedule',
            name='panelist',
            field=models.ManyToManyField(blank=True, to='registration.panelist'),
        ),
    ]
