# Generated by Django 5.1.4 on 2024-12-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_programschedule_chairperson_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairperson',
            options={'verbose_name_plural': 'Chairperson'},
        ),
        migrations.AddField(
            model_name='event',
            name='slogan',
            field=models.CharField(default='Empowering Survivors, Education & Support', max_length=200),
        ),
    ]
