# Generated by Django 5.1.4 on 2024-12-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_chairperson_options_event_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschedule',
            name='is_parallel',
            field=models.BooleanField(default=False),
        ),
    ]
