# Generated by Django 5.1.4 on 2024-12-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_programschedule_is_parallel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programschedule',
            name='is_parallel',
        ),
    ]
