# Generated by Django 5.1.4 on 2024-12-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_programschedule_is_parallel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('og_image', models.ImageField(upload_to='og_images/')),
                ('og_url', models.URLField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='registration.event')),
            ],
        ),
    ]
