# Generated by Django 5.1.4 on 2024-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_eventmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmetadata',
            name='og_url',
        ),
        migrations.AlterField(
            model_name='eventmetadata',
            name='keywords',
            field=models.CharField(help_text='Enter Keywords seperated by comma', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventmetadata',
            name='og_image',
            field=models.ImageField(upload_to='static/images/og_images/'),
        ),
    ]
