# Generated by Django 5.1.4 on 2024-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_eventmetadata_og_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='keywords',
            field=models.CharField(blank=True, help_text='Enter Keywords seperated by comma', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/og_images/'),
        ),
    ]
