# Generated by Django 5.1.4 on 2024-12-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_event_description_alter_event_keywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventMetadata',
        ),
    ]
