# Generated by Django 5.1.4 on 2024-12-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_delete_eventmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/event_logos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=10),
        ),
    ]
