# Generated by Django 5.1.4 on 2024-12-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
