# Generated by Django 5.1.4 on 2024-12-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_event_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
