# Generated by Django 5.1.4 on 2024-12-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_alter_event_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Starting Soon', 'Starting Soon')], default='Open', max_length=50),
        ),
    ]
