# Generated by Django 5.1.4 on 2024-12-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_event_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
