# Generated by Django 5.1.4 on 2024-12-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_statuses', to='registration.participant'),
        ),
    ]
