# Generated by Django 5.1.4 on 2024-12-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_alter_paymentstatus_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
    ]
