# Generated by Django 5.1.4 on 2024-12-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_paymentstatus_amount_paymentstatus_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name_plural': 'Payment Status'},
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
    ]
