# Generated by Django 5.1.4 on 2024-12-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
