# Generated by Django 5.1.4 on 2024-12-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_alter_participant_email_alter_participant_phone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('email', 'event'), ('phone', 'event')},
        ),
    ]
