# Generated by Django 5.1.4 on 2024-12-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractsubmission',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
