# Generated by Django 5.1.4 on 2024-12-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_alter_abstractsubmission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('initiated', 'Initiated'), ('failed', 'Failed')], default='unpaid', max_length=10),
        ),
    ]
