# Generated by Django 5.1.4 on 2024-12-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_paymentstatus_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
