# Generated by Django 5.1.4 on 2024-12-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_alter_paymentstatus_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='invoice_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
