# Generated by Django 5.1.4 on 2024-12-31 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_alter_paymentstatus_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('not_issued', 'Not Issued')], default='not_issued', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_kit', to='registration.paymentstatus')),
            ],
            options={
                'verbose_name_plural': 'Registration Kits',
            },
        ),
    ]
