# Generated by Django 5.1.4 on 2024-12-31 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_registrationkit'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationkit',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registration_kits', to='registration.event'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='registrationkit',
            unique_together={('event', 'payment_status')},
        ),
    ]
