# Generated by Django 5.1.4 on 2024-12-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_registrationkit_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('trx_id', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=50)),
                ('payment_create_time', models.DateTimeField()),
                ('payment_execute_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('intent', models.CharField(max_length=20)),
                ('merchant_invoice', models.CharField(max_length=255)),
                ('transaction_status', models.CharField(max_length=50)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verification_status', models.CharField(max_length=50)),
                ('payer_reference', models.CharField(max_length=255)),
                ('payer_type', models.CharField(max_length=50)),
                ('status_code', models.CharField(max_length=10)),
                ('status_message', models.CharField(max_length=255)),
            ],
        ),
    ]
