# Generated by Django 5.1.4 on 2024-12-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_bkashdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentstatus',
            old_name='invoice_number',
            new_name='merchant_invoice_number',
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('completed', 'Completed'), ('unpaid', 'Unpaid'), ('initiated', 'Initiated'), ('failed', 'Failed')], default='unpaid', max_length=10),
        ),
    ]
