# Generated by Django 5.1.4 on 2025-01-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_rename_invoice_number_paymentstatus_merchant_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='trxID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
