# Generated by Django 5.1.4 on 2025-01-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_paymentstatus_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='invoice',
        ),
    ]
