# Generated by Django 5.1.4 on 2025-01-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_remove_paymentstatus_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
