# Generated by Django 5.1.4 on 2025-01-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0046_paymentstatus_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
