# Generated by Django 5.1.4 on 2025-01-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_paymentstatus_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='media/invoices/'),
        ),
    ]
