# Generated by Django 5.1.4 on 2025-01-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_alter_paymentstatus_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_hero_image',
            field=models.ImageField(blank=True, help_text='Upload an image for the hero section of the event page. Recomended size: 1920x1080', null=True, upload_to='media/event_images/'),
        ),
    ]
