# Generated by Django 5.1.4 on 2025-01-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_event_event_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='modal_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/modal_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_hero_image',
            field=models.ImageField(blank=True, help_text='Upload an image for the hero section of the event page. Recomended size: 1920x1080', null=True, upload_to='media/hero_images/'),
        ),
    ]
