# Generated by Django 5.1.4 on 2025-01-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0050_event_modal_image_alter_event_event_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='category',
            field=models.CharField(blank=True, choices=[('Title', 'Title'), ('Platinum', 'Platinum'), ('Golden', 'Golden'), ('Silver', 'Silver'), ('Logistics', 'Logistics'), ('Media', 'Media'), ('IT', 'IT'), ('Event', 'Event')], max_length=200, null=True),
        ),
    ]
