# Generated by Django 5.1.4 on 2025-01-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_alter_sponsor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschedule',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
