# Generated by Django 5.1.4 on 2025-01-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0052_programschedule_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkashdata',
            name='payment_create_time',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bkashdata',
            name='payment_execute_time',
            field=models.CharField(max_length=150),
        ),
    ]
