# Generated by Django 5.1.4 on 2025-02-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_alter_bkashdata_payment_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSchedulePdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_image', models.ImageField(blank=True, null=True, upload_to='media/event_images/')),
                ('schedule_pdf', models.FileField(blank=True, null=True, upload_to='media/event_pdfs/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
        ),
    ]
