# Generated by Django 5.1.4 on 2025-02-26 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0054_programschedulepdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAbstractBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_book', models.FileField(blank=True, null=True, upload_to='media/abstract_books/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
        ),
        migrations.CreateModel(
            name='UploadNoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_book', models.ImageField(blank=True, null=True, upload_to='media/event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
        ),
    ]
