# Generated by Django 5.1.4 on 2025-03-10 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0055_uploadabstractbook_uploadnotebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_body',
            field=models.TextField(blank=True, help_text='Thank You email body text', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Thank You email subject text', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ThankYouEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('email_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('registration_kit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thank_you_email', to='registration.registrationkit')),
            ],
        ),
    ]
