# Generated by Django 5.1.4 on 2025-03-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0056_event_email_body_event_email_subject_thankyouemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='media/event_images/')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('text', 'Text (Simple Open-ended)'), ('radio', 'Radio (Single-choice)'), ('matrix', 'Matrix (Row and Column)')], default='text', max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('rows', models.TextField(blank=True, help_text="For matrix-type questions: Enter rows separated by commas, e.g., 'Welcome Kit, Venue, Food'.", null=True)),
                ('columns', models.TextField(blank=True, help_text="For matrix-type questions: Enter columns separated by commas, e.g., '1, 2, 3, 4, 5, N/A'.", null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ManyToManyField(related_name='feedback_questions', to='registration.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.feedbackquestion')),
            ],
        ),
    ]
