# Generated by Django 5.1.4 on 2025-04-04 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0057_certificate_feedbackquestion_feedbackresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractsubmission',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to='media/presentation_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])]),
        ),
    ]
