# Generated by Django 5.1.4 on 2025-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0058_abstractsubmission_presentation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_publication_tab',
            field=models.BooleanField(default=False, help_text='Show or hide the Publication tab on the event page.'),
        ),
    ]
