# Generated by Django 5.1.4 on 2025-07-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0060_bulkemail_bulkemailsreporting_emailgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_required',
            field=models.BooleanField(default=True, help_text='Check if payment is required'),
        ),
    ]
