# Generated by Django 5.1.4 on 2025-12-04 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0062_alter_abouttheconference_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abouttheconference",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/about_images/"
            ),
        ),
        migrations.AlterField(
            model_name="abstractsubmission",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/abstract_images/"
            ),
        ),
        migrations.AlterField(
            model_name="abstractsubmission",
            name="presentation_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/presentation_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "ppt", "pptx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="upload_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/event_images/"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for the hero section of the event page. Recomended size: 1920x1080",
                null=True,
                upload_to="media/hero_images/",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/event_logos/"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="modal_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/modal_images/"
            ),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(upload_to="media/event_images/"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/invitation_images/"
            ),
        ),
        migrations.AlterField(
            model_name="paymentstatus",
            name="invoice",
            field=models.FileField(blank=True, null=True, upload_to="media/invoices/"),
        ),
        migrations.AlterField(
            model_name="programschedulepdf",
            name="schedule_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/event_images/"
            ),
        ),
        migrations.AlterField(
            model_name="programschedulepdf",
            name="schedule_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="media/event_pdfs/"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/sponsor_images/"
            ),
        ),
        migrations.AlterField(
            model_name="uploadabstractbook",
            name="abstract_book",
            field=models.FileField(
                blank=True, null=True, upload_to="media/abstract_books/"
            ),
        ),
        migrations.AlterField(
            model_name="uploadnotebook",
            name="note_book",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/event_images/"
            ),
        ),
    ]
