# Generated by Django 5.1.4 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_alter_abouttheconference_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='member_registration_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Allow approved active BSBCS members to register through the member flow',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='member_registration_fee',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Optional member-only event fee. Leave blank or set 0 for free member attendance.',
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='participant',
            name='registration_type',
            field=models.CharField(
                choices=[('regular', 'Regular'), ('member', 'Member')],
                default='regular',
                max_length=20,
            ),
        ),
    ]
