# Generated by Django 5.1.4 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0064_event_member_registration_and_participant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_audience',
            field=models.CharField(
                choices=[('all', 'All users'), ('members_only', 'Members only')],
                default='all',
                help_text='Choose who can register for this event.',
                max_length=20,
            ),
        ),
    ]
