# Generated by Django 5.1.4 on 2026-05-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0071_corporatepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="design_mode",
            field=models.CharField(
                choices=[("image", "Uploaded Image"), ("html", "HTML Design")],
                default="image",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="event_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="certificates/event_logos/"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="organizer_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="certificates/logos/"
            ),
        ),
        migrations.CreateModel(
            name="CertificateSignatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("organization", models.TextField(blank=True, null=True)),
                (
                    "signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificates/signatures/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatories",
                        to="registration.certificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate signatory",
                "verbose_name_plural": "Certificate signatories",
                "ordering": ["order", "id"],
            },
        ),
    ]
