# Generated by Django 5.1.4 on 2026-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration",
            "0072_certificate_design_mode_certificate_event_logo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="co_organizer_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="certificates/logos/"
            ),
        ),
    ]
