# Generated by Django 5.1.4 on 2026-05-19 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0073_certificate_co_organizer_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("degree", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("country", models.CharField(default="Bangladesh", max_length=100)),
                ("biography", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/program_people/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Person",
                "verbose_name_plural": "Program People",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProgramSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_sessions",
                        to="registration.event",
                    ),
                ),
                (
                    "hall_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_sessions",
                        to="registration.hallroom",
                    ),
                ),
                (
                    "program_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_sessions",
                        to="registration.programday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Program Session",
                "verbose_name_plural": "Smart Program Sessions",
                "ordering": ["program_day__date", "start_time", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProgramSessionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Use this for non-abstract talks or manual titles.",
                        max_length=400,
                        null=True,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "abstract_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_session_items",
                        to="registration.abstractsubmission",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="registration.programsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Program Item",
                "verbose_name_plural": "Smart Program Items",
                "ordering": ["order", "start_time", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProgramSessionFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chairperson", "Chairperson"),
                            ("moderator", "Moderator"),
                            ("panelist", "Panelist"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_roles",
                        to="registration.programperson",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_roles",
                        to="registration.programsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Faculty Role",
                "verbose_name_plural": "Session Faculty Roles",
                "ordering": ["role", "order", "person__name"],
                "unique_together": {("session", "person", "role")},
            },
        ),
        migrations.CreateModel(
            name="ProgramItemFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("speaker", "Speaker"),
                            ("presenter", "Presenter"),
                            ("discussant", "Discussant"),
                        ],
                        default="speaker",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_roles",
                        to="registration.programperson",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_roles",
                        to="registration.programsessionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Faculty Role",
                "verbose_name_plural": "Item Faculty Roles",
                "ordering": ["role", "order", "person__name"],
                "unique_together": {("item", "person", "role")},
            },
        ),
    ]
