# Generated by Django 5.1.4 on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0074_programperson_programsession_programsessionitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programsession",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_sessions",
                to="registration.timeslot",
            ),
        ),
    ]
