# Generated by Django 5.1.4 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0075_programsession_time_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="label",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("session", "Session slot"),
                    ("tea_break", "Tea break"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("ceremony", "Ceremony"),
                    ("custom", "Custom block"),
                ],
                default="session",
                max_length=24,
            ),
        ),
    ]
