# Generated by Django 5.1.4 on 2026-05-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0076_timeslot_label_timeslot_slot_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramTalkSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talk_slots",
                        to="registration.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Talk Slot",
                "verbose_name_plural": "Program Talk Slots",
                "ordering": ["time_slot__start_time", "order", "start_time", "id"],
                "unique_together": {("time_slot", "start_time", "end_time")},
            },
        ),
        migrations.AddField(
            model_name="programsessionitem",
            name="talk_slot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_item",
                to="registration.programtalkslot",
            ),
        ),
    ]
