# Generated by Django 5.1.4 on 2026-05-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0077_programtalkslot_programsessionitem_talk_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='programperson',
            name='profile',
            field=models.OneToOneField(
                blank=True,
                help_text='Optional website profile used to create or identify this program person.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='program_person',
                to='registration.userprofile',
            ),
        ),
    ]
