# Generated by Django 5.1.4 on 2026-05-22

from django.db import migrations, models


def add_existing_schedule_people_to_events(apps, schema_editor):
    ProgramSessionFaculty = apps.get_model('registration', 'ProgramSessionFaculty')
    ProgramItemFaculty = apps.get_model('registration', 'ProgramItemFaculty')
    ProgramPerson = apps.get_model('registration', 'ProgramPerson')
    through_model = ProgramPerson.events.through

    event_person_pairs = set(
        ProgramSessionFaculty.objects.values_list('session__event_id', 'person_id')
    )
    event_person_pairs.update(
        ProgramItemFaculty.objects.values_list('item__session__event_id', 'person_id')
    )
    through_model.objects.bulk_create(
        [
            through_model(event_id=event_id, programperson_id=person_id)
            for event_id, person_id in event_person_pairs
            if event_id and person_id
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0078_programperson_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='programperson',
            name='events',
            field=models.ManyToManyField(
                blank=True,
                help_text='Events where this person is available for program scheduling.',
                related_name='program_people',
                to='registration.event',
            ),
        ),
        migrations.RunPython(add_existing_schedule_people_to_events, migrations.RunPython.noop),
    ]
