# Generated by Django 5.1.4 on 2026-06-01 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0079_programperson_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramPersonEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("send_count", models.PositiveIntegerField(default=0)),
                ("last_session_count", models.PositiveIntegerField(default=0)),
                ("last_talk_count", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_person_email_logs",
                        to="registration.event",
                    ),
                ),
                (
                    "last_sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_person_emails_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_email_logs",
                        to="registration.programperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Person Email Log",
                "verbose_name_plural": "Program Person Email Logs",
                "ordering": ["event__start_date", "person__name"],
                "unique_together": {("event", "person")},
            },
        ),
    ]
