# Generated by Django 5.1.4 on 2026-06-02 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0080_programpersonemaillog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkemail",
            name="audience_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual recipients"),
                    ("active_users", "Active website users"),
                    ("email_group", "Email group"),
                    ("event_participants", "Event participants"),
                    (
                        "event_unpaid",
                        "Approved event participants with pending payment",
                    ),
                    ("abstract_submitters", "Abstract submitters"),
                    ("corporate_contacts", "Corporate contacts"),
                ],
                default="manual",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="bulkemail",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bulk_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bulkemail",
            name="email_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulk_emails",
                to="registration.emailgroup",
            ),
        ),
        migrations.AddField(
            model_name="bulkemail",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulk_emails",
                to="registration.event",
            ),
        ),
        migrations.AddField(
            model_name="bulkemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("recipients_ready", "Recipients ready"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("partial", "Partially sent"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="bulkemail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="BulkEmailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=180, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("user", "Website user"),
                            ("email_group", "Email group"),
                            ("participant", "Participant"),
                            ("abstract", "Abstract submitter"),
                            ("corporate", "Corporate"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "abstract_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_email_recipients",
                        to="registration.abstractsubmission",
                    ),
                ),
                (
                    "bulk_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="registration.bulkemail",
                    ),
                ),
                (
                    "corporate_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_email_recipients",
                        to="registration.corporateaccount",
                    ),
                ),
                (
                    "corporate_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_email_recipients",
                        to="registration.corporateaccountrequest",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_email_recipients",
                        to="registration.participant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_email_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_email_recipients",
                        to="registration.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["email"],
                "unique_together": {("bulk_email", "email")},
            },
        ),
        migrations.CreateModel(
            name="BulkEmailSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bulk_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_logs",
                        to="registration.bulkemail",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="send_logs",
                        to="registration.bulkemailrecipient",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_email_send_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
