# Generated by Django 5.1.4 on 2026-06-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0082_participantemaillog"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentstatus",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="registration_qr_codes/"
            ),
        ),
        migrations.AddField(
            model_name="paymentstatus",
            name="qr_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
