# Generated by Django 5.1.4 on 2026-06-08 16:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0083_paymentstatus_qr_code_paymentstatus_qr_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PresentationUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("abstract", "Abstract submission"),
                            ("session_item", "Program talk / activity"),
                            ("session_role", "Session faculty role"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("role_label", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "presenter_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="media/presentation_uploads/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "ppt", "pptx"]
                            )
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abstract_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presentation_uploads",
                        to="registration.abstractsubmission",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentation_uploads",
                        to="registration.event",
                    ),
                ),
                (
                    "program_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presentation_uploads",
                        to="registration.programperson",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presentation_uploads",
                        to="registration.programsession",
                    ),
                ),
                (
                    "session_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presentation_uploads",
                        to="registration.programsessionitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presentation_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presentation Upload",
                "verbose_name_plural": "Presentation Uploads",
                "ordering": [
                    "event__start_date",
                    "session__start_time",
                    "session_item__order",
                    "title",
                ],
            },
        ),
    ]
