# Generated by Django 5.1.4 on 2026-06-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0084_presentationupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="company_person_registration_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow company people registration for this event.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="company_person_registration_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional company person registration fee.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
