# Generated by Django 5.1.4 on 2026-06-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0085_event_company_person_registration_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateaccount",
            name="company_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/corporate_logos/"
            ),
        ),
    ]
