# Generated by Django 5.1.4 on 2026-06-09 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0086_corporateaccount_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateeventregistration",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Attendee"),
                    ("company_person", "Company Person"),
                    ("complementary", "Complementary"),
                ],
                default="regular",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("member", "Member"),
                    ("company_person", "Company Person"),
                    ("complementary", "Complementary"),
                ],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CorporateEventComplementaryQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of free registrations granted."
                    ),
                ),
                (
                    "corporate_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complementary_quotas",
                        to="registration.corporateaccount",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complementary_quotas",
                        to="registration.event",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Corporate Complementary Quotas",
                "unique_together": {("corporate_account", "event")},
            },
        ),
    ]
