# Generated by Django 5.1.4 on 2026-06-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0087_corporateeventregistration_registration_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkemail",
            name="audience_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual recipients"),
                    ("active_users", "Active website users"),
                    ("email_group", "Email group"),
                    ("event_participants", "Event participants"),
                    (
                        "event_unpaid",
                        "Approved event participants with pending payment",
                    ),
                    (
                        "membership_unpaid",
                        "Approved members with pending membership payment",
                    ),
                    ("abstract_submitters", "Abstract submitters"),
                    ("corporate_contacts", "Corporate contacts"),
                ],
                default="manual",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="bulkemailrecipient",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("user", "Website user"),
                    ("email_group", "Email group"),
                    ("participant", "Participant"),
                    ("membership", "Membership"),
                    ("abstract", "Abstract submitter"),
                    ("corporate", "Corporate"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
    ]
