# Generated by Django 5.1.4 on 2026-06-22 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0094_speaker_outreach_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerOutreachTemplatePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("intro_body", models.TextField(blank=True, null=True)),
                ("closing_body", models.TextField(blank=True, null=True)),
                ("airfare_body", models.TextField(blank=True, null=True)),
                ("hotel_body", models.TextField(blank=True, null=True)),
                ("allowance_body", models.TextField(blank=True, null=True)),
                ("local_transport_body", models.TextField(blank=True, null=True)),
                ("special_support_body", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="speaker_outreach_template_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Speaker outreach template preset",
                "verbose_name_plural": "Speaker outreach template presets",
                "ordering": ["name", "-updated_at"],
            },
        ),
    ]
