# Generated by Django 5.1.4 on 2026-06-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0096_emailauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailQuotaLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(default="global", max_length=40, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email quota lock",
                "verbose_name_plural": "Email quota locks",
            },
        ),
        migrations.CreateModel(
            name="EmailQuotaReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_key", models.CharField(db_index=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("approval", "Approval emails"),
                            ("registration", "Registration emails"),
                            ("membership", "Membership emails"),
                            ("bulk_email", "Bulk emails"),
                            ("thank_you", "Thank-you emails"),
                            ("invoice", "Invoice emails"),
                            ("program", "Program emails"),
                            ("speaker_certificate", "Speaker certificate emails"),
                            ("speaker_outreach", "Speaker outreach emails"),
                            ("corporate", "Corporate emails"),
                            ("system", "System emails"),
                        ],
                        max_length=40,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=320)),
                ("recipient_key", models.CharField(db_index=True, max_length=320)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("consumed", "Consumed"),
                            ("released", "Released"),
                        ],
                        db_index=True,
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email quota reservation",
                "verbose_name_plural": "Email quota reservations",
                "ordering": ["-reserved_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reservation_key", "recipient_key"),
                        name="unique_email_quota_reservation_key_recipient",
                    )
                ],
            },
        ),
    ]
