# Generated by Codex on 2026-07-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0101_alter_chestcard_file_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone_numbers', models.TextField(help_text='One phone number per line or comma-separated list')),
            ],
        ),
        migrations.CreateModel(
            name='BulkSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience_type', models.CharField(choices=[('manual', 'Manual recipients'), ('active_users', 'Active website users'), ('phone_group', 'Phone group'), ('event_participants', 'Event participants'), ('event_unpaid', 'Approved event participants with pending payment'), ('membership_unpaid', 'Approved members with pending membership payment'), ('abstract_submitters', 'Abstract submitters'), ('corporate_contacts', 'Corporate contacts')], default='manual', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recipients_ready', 'Recipients ready'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially sent')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bulk_sms_campaigns', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_campaigns', to='registration.event')),
                ('phone_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_campaigns', to='registration.phonegroup')),
            ],
        ),
        migrations.CreateModel(
            name='BulkSMSRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('raw_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=180, null=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('user', 'Website user'), ('phone_group', 'Phone group'), ('participant', 'Participant'), ('membership', 'Membership'), ('abstract', 'Abstract submitter'), ('corporate', 'Corporate')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abstract_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_recipients', to='registration.abstractsubmission')),
                ('bulk_sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='registration.bulksms')),
                ('corporate_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_recipients', to='registration.corporateaccount')),
                ('corporate_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_recipients', to='registration.corporateaccountrequest')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_recipients', to='registration.participant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_recipients', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_recipients', to='registration.userprofile')),
            ],
            options={
                'ordering': ['phone'],
                'unique_together': {('bulk_sms', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='BulkSMSSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('provider_status', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='registration.bulksms')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='registration.bulksmsrecipient')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_sms_send_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
