# Generated by Django 5.1.4 on 2026-07-11 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0104_systemsmstemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="enable_food_tokens",
            field=models.BooleanField(
                default=False,
                help_text="Enable dashboard generation and QR redemption of food tokens for this event.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="food_token_max_redemptions",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Default allowed food-token scans per approved paid participant.",
            ),
        ),
        migrations.AlterField(
            model_name="systemsmstemplate",
            name="sms_type",
            field=models.CharField(
                choices=[("masking", "Masking"), ("non_masking", "Non-masking")],
                default="non_masking",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FoodToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="food_tokens/generated_pdfs/",
                    ),
                ),
                (
                    "generated_png",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="food_tokens/generated_png/",
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("design_updated_at", models.DateTimeField(blank=True, null=True)),
                ("allowed_redemptions", models.PositiveIntegerField(default=1)),
                ("redeemed_count", models.PositiveIntegerField(default=0)),
                ("last_redeemed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generated", "Generated"),
                            ("outdated", "Outdated"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_tokens",
                        to="registration.event",
                    ),
                ),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_token",
                        to="registration.participant",
                    ),
                ),
                (
                    "payment_status",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_token",
                        to="registration.paymentstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food token",
                "verbose_name_plural": "Food tokens",
            },
        ),
        migrations.CreateModel(
            name="FoodTokenDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design_mode",
                    models.CharField(
                        choices=[
                            ("overlay", "Preprinted overlay"),
                            ("html", "HTML design"),
                        ],
                        default="html",
                        max_length=20,
                    ),
                ),
                (
                    "width_mm",
                    models.DecimalField(decimal_places=2, default=90, max_digits=6),
                ),
                (
                    "height_mm",
                    models.DecimalField(decimal_places=2, default=55, max_digits=6),
                ),
                ("dpi", models.PositiveIntegerField(default=300)),
                (
                    "badge_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional heading like FOOD TOKEN or LUNCH TOKEN.",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("accent_color", models.CharField(default="#1769c2", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#f8fbff", max_length=20),
                ),
                (
                    "overlay_reference_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional on-screen reference image for preprinted coupon alignment.",
                        null=True,
                        upload_to="food_tokens/overlay_reference/",
                    ),
                ),
                (
                    "html_background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="food_tokens/html_backgrounds/"
                    ),
                ),
                (
                    "name_x_mm",
                    models.DecimalField(decimal_places=2, default=10, max_digits=6),
                ),
                (
                    "name_y_mm",
                    models.DecimalField(decimal_places=2, default=18, max_digits=6),
                ),
                (
                    "name_width_mm",
                    models.DecimalField(decimal_places=2, default=46, max_digits=6),
                ),
                (
                    "name_height_mm",
                    models.DecimalField(decimal_places=2, default=14, max_digits=6),
                ),
                (
                    "qr_x_mm",
                    models.DecimalField(decimal_places=2, default=60, max_digits=6),
                ),
                (
                    "qr_y_mm",
                    models.DecimalField(decimal_places=2, default=11, max_digits=6),
                ),
                (
                    "qr_size_mm",
                    models.DecimalField(decimal_places=2, default=22, max_digits=6),
                ),
                ("font_size_pt", models.PositiveIntegerField(default=16)),
                ("font_color", models.CharField(default="#0f172a", max_length=20)),
                (
                    "text_align",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                ("show_event_name", models.BooleanField(default=True)),
                ("show_organization", models.BooleanField(default=False)),
                ("show_invoice_number", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_token_design",
                        to="registration.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food token design",
                "verbose_name_plural": "Food token designs",
            },
        ),
        migrations.CreateModel(
            name="FoodTokenRedemptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_token_redemption_logs",
                        to="registration.event",
                    ),
                ),
                (
                    "food_token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemption_logs",
                        to="registration.foodtoken",
                    ),
                ),
                (
                    "payment_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_token_redemption_logs",
                        to="registration.paymentstatus",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="food_token_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Food token redemption log",
                "verbose_name_plural": "Food token redemption logs",
                "ordering": ["-redeemed_at", "-id"],
            },
        ),
    ]
