# Generated by Django 5.1.4 on 2026-07-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration', '0105_event_enable_food_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDriveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='media/event_drive_thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event')),
            ],
        ),
    ]
