# Generated by Django 5.1.4 on 2026-07-20 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0108_finance_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financeexpense",
            name="expense_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="financevendorpayment",
            name="payment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
