# Generated by Django 5.1.4 on 2026-07-20 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0109_alter_financeexpense_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_finance_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_finance_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financevendorpayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financevendorpayment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_finance_vendor_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financevendorpayment',
            name='paid_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financevendorpayment',
            name='paid_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_finance_vendor_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financevendorpayment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financevendorpayment',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_finance_vendor_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]

