# Generated by Django 5.1.4 on 2026-07-24 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0111_finance_accounts_cash_and_other_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financetransfer",
            name="transfer_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
