# Generated by Django 5.1.4 on 2026-07-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0115_bulkemail_event_paid_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulksms",
            name="audience_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual recipients"),
                    ("active_users", "Active website users"),
                    ("phone_group", "Phone group"),
                    ("event_participants", "Event participants"),
                    (
                        "event_unpaid",
                        "Approved event participants with pending payment",
                    ),
                    (
                        "membership_unpaid",
                        "Approved members with pending membership payment",
                    ),
                    ("abstract_submitters", "Abstract submitters"),
                    ("corporate_contacts", "Corporate contacts"),
                ],
                default="manual",
                max_length=40,
            ),
        ),
    ]
