# Generated by Django 5.1.4 on 2026-08-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0117_bulksms_event_paid_audience"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=180, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=40, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sponsor company",
                "verbose_name_plural": "Sponsor company list",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="financesponsorshipincome",
            name="sponsor_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finance_income_rows",
                to="registration.sponsorcompany",
            ),
        ),
    ]
